# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Mappiness.
tagline:             'map the happiness.'
description:		 "밟아가는 여정. 그 족적."
url:                 http://skdy33.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sangheon Lee
  email:             skdy3333@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
